pre-release r2.1
camaraproject/Tenure pull request #18
Opened 2024-12-18 17:25 UTC by fernandopradocabrillo

#### What type of PR is this?

Add one of the following kinds:
* subproject management

#### What this PR does / why we need it:
Complete preparations for first pre-release of Tenure API for meta Spring25

2024-12-18 18:43 UTC, hdamker commented
@fernandopradocabrillo: I've created the release review issue for this pre-release in Release Management. You submitted the first API version which claims to be compliant to Commonalities v0.5.0-alpha.1. Congratulations!

An initial comment: This is the first pre-release overall of this API repository, so the number should be r1.1, not r1.2.

2024-12-19 08:32 UTC, GillesInnov35 approved these changes
Thanks Fernando. 
I saw comment from Herbert on r2.1, di you know if an update is waiting

2024-12-19 08:49 UTC, fernandopradocabrillo commented
> @fernandopradocabrillo: I've created the release review issue for this pre-release in Release Management. You submitted the first API version which claims to be compliant to Commonalities v0.5.0-alpha.1. Congratulations!
> 
> An initial comment: This is the first pre-release overall of this API repository, so the number should be r1.1, not r1.2.

Hi @hdamker ! I'll update the release version, I wasn't sure if it should be r2.1 or r1.1, I thought that the 2.X referred to the number of the meta release, being the Spring25 the second one.

2024-12-19 09:08 UTC, GillesInnov35 approved these changes
Thanks Fernando

2024-12-19 09:32 UTC, eric-murray commented
@fernandopradocabrillo 
For a release candidate, there should already be test definitions. Do you plan to add these to this PR?

If not, you can make it an alpha release for now

2024-12-19 09:35 UTC, eric-murray commented on code/API_definitions/kyc-tenure.yaml
>              This attribute may be omitted from the response set where value is not known on the local MNO system.
```suggestion
            This attribute may be omitted from the response set where value is not known on the local network operator system.
```

2024-12-19 11:39 UTC, fernandopradocabrillo commented
> @fernandopradocabrillo For a release candidate, there should already be test definitions. Do you plan to add these to this PR?
> 
> If not, you can make it an alpha release for now

You are right, I didn't realize. I've provided an initial basic (or not so basic haha) test plan in PR #19. Take a look and let me know if it is enough.

2024-12-19 11:56 UTC, hdamker commented
> Hi @hdamker ! I'll update the release version, I wasn't sure if it should be r2.1 or r1.1, I thought that the 2.X referred to the number of the meta release, being the Spring25 the second one.

That was for some time also my thought, but the definition is clear, that the first release of an API repository starts with r1.1, see https://github.com/camaraproject/ReleaseManagement/blob/main/documentation/API_Release_Guidelines.md#api-release-numbering.

2025-01-07 08:37 UTC, GillesInnov35 submitted a review, later dismissed
Thanks

2025-01-14 00:37 UTC, tanjadegroot requested changes

2025-01-14 00:37 UTC, tanjadegroot commented on code/API_definitions/kyc-tenure.yaml
line 510: "where value is not known on the local network operator system."
this sentence could either be cut after "not know", but in general, as the CSP would have this data, but may not want to expose it, it could be just say "if the value is not available" or '"if the value is not available from the CSP owning the subscriber". 
I would not refer to "the local network operator system" as 1) the API call may be made to an aggregator (so not local) and 2) the word "system" seems not very applicable in this context.

2025-01-14 00:37 UTC, tanjadegroot commented on CHANGELOG.md
> +**Please be aware that the project will have frequent updates to the main branch. There are no compatibility guarantees associated with code in any branch, including main, until it has been released.
This section does not have the text from the latest version which has 4 bullets. Please copy the latest text from here: https://github.com/camaraproject/ReleaseManagement/blob/main/documentation/CHANGELOG_TEMPLATE.md

2025-01-14 00:37 UTC, tanjadegroot commented on documentation/API_documentation/kyc-tenure-API-Readiness-Checklist.md
> +|  2 | Design guidelines from Commonalities applied |   O   |         M         |    M    |    M   |  Y   | [r1.1](https://github.com/camaraproject/Commonalities/releases/tag/r1.1) |
This link should point to the r2.1 release of Commonalities: https://github.com/camaraproject/Commonalities/releases/tag/r2.1

2025-01-14 00:37 UTC, tanjadegroot commented on documentation/API_documentation/kyc-tenure-API-Readiness-Checklist.md
> +|  3 | Guidelines from ICM applied                  |   O   |         M         |    M    |    M   |  Y   | [r1.1](https://github.com/camaraproject/IdentityAndConsentManagement/releases/tag/r1.1) |
This link should point to the r2.1 release of ICM: https://github.com/camaraproject/IdentityAndConsentManagement/releases/tag/r2.1

2025-01-14 00:37 UTC, tanjadegroot commented on documentation/API_documentation/kyc-tenure-API-Readiness-Checklist.md
> +|  7 | Basic API test cases & documentation         |   O   |         M         |    M    |    M   |  tbd |   |
The basic test case .feature file needs to be provided for the release candidate.

2025-01-14 00:56 UTC, tanjadegroot commented
Please also check that the error code definitions are aligned with the latest requirements of Commonalities and data types https://github.com/camaraproject/Commonalities/blob/main/artifacts/CAMARA_common.yaml

2025-01-14 11:10 UTC, eric-murray commented on code/API_definitions/kyc-tenure.yaml
>          default: https://localhost:443
The ICM guidelines state that TLS is mandatory, so using an HTTP example for `apiRoot` is somewhat misleading. Port 443 is the default for HTTPS, so it could be omitted altogether. However, I don't think anyone will be mislead by explicitly including it, and including it shows how a different port could be specified. I would expect the majority of API calls to use port 443 in practice.

2025-01-14 15:09 UTC, hdamker commented on code/API_definitions/kyc-tenure.yaml
>          default: https://localhost:443
> I would expect the majority of API calls to use port 443 in practice.

As localhost will be most probably only used for testing purposes it might make sense to use port number outside the well-known port numbers (0-1023) to avoid conflicts with existing services. And https would require at least a self-signed certificate ...

2025-01-14 16:13 UTC, fernandopradocabrillo commented on code/API_definitions/kyc-tenure.yaml
text proposed:

```
Verifies the length of tenure, based on a provided date, for a network subscriber to establish a level of trust for the network subscription identifier.
```

2025-01-14 16:16 UTC, fernandopradocabrillo commented on code/API_definitions/kyc-tenure.yaml
Changed TenureDate component to Tenure for clarity

2025-01-14 16:18 UTC, fernandopradocabrillo commented on code/API_definitions/kyc-tenure.yaml
Agree, we'll simplify

```
This attribute may be omitted from the response set if the information is not available
```

2025-01-14 16:26 UTC, fernandopradocabrillo commented on documentation/API_documentation/kyc-tenure-API-Readiness-Checklist.md
> +|  7 | Basic API test cases & documentation         |   O   |         M         |    M    |    M   |  tbd |   |
Hi @tanjadegroot, the test plan is in [this](https://github.com/camaraproject/Tenure/pull/19) right now under review, should we include a reference to the PR or just place the final link and wait for the test plan to be merge before merging this one? Thanks!

2025-01-14 16:32 UTC, fernandopradocabrillo commented
> Please also check that the error code definitions are aligned with the latest requirements of Commonalities and data types https://github.com/camaraproject/Commonalities/blob/main/artifacts/CAMARA_common.yaml

Thanks @tanjadegroot for the review, I've made the changes.
Regarding this last one, I think we are good with the new model error that now includes the codes as an enum

2025-01-16 09:51 UTC, eric-murray commented on code/API_definitions/kyc-tenure.yaml
>          default: https://localhost:443
Actually, I doubt localhost would be used much even for testing. Certainly Vodafone would not allow me to copy the pre-prod environment to my laptop. Our pre-prod environment has its own FQDN (using port 443, of course!).

Maybe https://example.com:443 (or https://example.com:8443 for a "non-standard" port example) would be better "production" examples.

I'll raise the issue in Commonalities once the current meta-release guidelines are complete. I don't think it really matters that much, but would be good to get a consistent "default" that all APIs are happy to use.

2025-01-16 12:24 UTC, grgpapadopoulos approved these changes

2025-01-16 14:14 UTC, tanjadegroot commented on documentation/API_documentation/kyc-tenure-API-Readiness-Checklist.md
> +|  7 | Basic API test cases & documentation         |   O   |         M         |    M    |    M   |  tbd |   |
Looks good, I put some comments on that PR (typos)

2025-01-16 14:19 UTC, tanjadegroot commented
with the test file  merged, and the corresponding link added to the API readiness checklist this PR is ok for release. LGTM

2025-01-17 11:36 UTC, tanjadegroot approved these changes
Great update - thanks ! all OK
please merge the test PR first and add the link to it in the readiness checklist. then LGTM for this PR.
don't forget to update the API release tracker (please follow the formatting (e.g. short links)

2025-01-20 10:52 UTC, fernandopradocabrillo commented
@eric-murray @GillesInnov35 updated with the changes included in #21

2025-01-20 10:57 UTC, GillesInnov35 submitted a review, later dismissed
LGTM Thanks

2025-01-20 21:03 UTC, tanjadegroot commented on documentation/API_documentation/kyc-tenure-API-Readiness-Checklist.md
> +|  3 | Guidelines from ICM applied                  |   O   |         M         |    M    |    M   |  Y   | [r1.1](https://github.com/camaraproject/IdentityAndConsentManagement/releases/tag/r2.1) |
r1.1 should be r2.1 according to the link

2025-01-20 21:03 UTC, tanjadegroot commented on documentation/API_documentation/kyc-tenure-API-Readiness-Checklist.md
> +|  2 | Design guidelines from Commonalities applied |   O   |         M         |    M    |    M   |  Y   | [r1.1](https://github.com/camaraproject/Commonalities/releases/tag/r2.1) |
r1.1 should be r2.1 according to the link

2025-01-21 08:05 UTC, luislopezcorpas approved these changes

2025-01-21 10:28 UTC, fernandopradocabrillo commented on documentation/API_documentation/kyc-tenure-API-Readiness-Checklist.md
> +|  3 | Guidelines from ICM applied                  |   O   |         M         |    M    |    M   |  Y   | [r1.1](https://github.com/camaraproject/IdentityAndConsentManagement/releases/tag/r2.1) |
the other way around, the link is not correct as this is the first pre-release of the repo. It is fixed now thanks

2025-01-21 10:28 UTC, fernandopradocabrillo commented on documentation/API_documentation/kyc-tenure-API-Readiness-Checklist.md
> +|  2 | Design guidelines from Commonalities applied |   O   |         M         |    M    |    M   |  Y   | [r1.1](https://github.com/camaraproject/Commonalities/releases/tag/r2.1) |
the other way around, the link is not correct as this is the first pre-release of the repo. It is fixed now thanks

2025-01-21 12:06 UTC, eric-murray requested changes
All good apart from the two links to Commonalities and ICM in the API Readiness Checklist

2025-01-21 12:06 UTC, eric-murray commented on documentation/API_documentation/kyc-tenure-API-Readiness-Checklist.md
> +|  2 | Design guidelines from Commonalities applied |   O   |         M         |    M    |    M   |  Y   | [r1.1](https://github.com/camaraproject/Commonalities/releases/tag/r1.1) |
```suggestion
|  2 | Design guidelines from Commonalities applied |   O   |         M         |    M    |    M   |  Y   | [r2.1](https://github.com/camaraproject/Commonalities/releases/tag/r2.1) |
```

2025-01-21 12:06 UTC, eric-murray commented on documentation/API_documentation/kyc-tenure-API-Readiness-Checklist.md
> +|  3 | Guidelines from ICM applied                  |   O   |         M         |    M    |    M   |  Y   | [r1.1](https://github.com/camaraproject/IdentityAndConsentManagement/releases/tag/r1.1) |
```suggestion
|  3 | Guidelines from ICM applied                  |   O   |         M         |    M    |    M   |  Y   | [r2.1](https://github.com/camaraproject/IdentityAndConsentManagement/releases/tag/r2.1) |
```

2025-01-21 16:39 UTC, fernandopradocabrillo commented on documentation/API_documentation/kyc-tenure-API-Readiness-Checklist.md
> +|  2 | Design guidelines from Commonalities applied |   O   |         M         |    M    |    M   |  Y   | [r1.1](https://github.com/camaraproject/Commonalities/releases/tag/r2.1) |
sorry, totally right, I saw it quickly and did it backwards

2025-01-21 16:40 UTC, fernandopradocabrillo commented
> All good apart from the two links to Commonalities and ICM in the API Readiness Checklist

Thanks @eric-murray, @tanjadegroot pointed it out and I messed up here. Should be fixed now

2025-01-21 17:03 UTC, GillesInnov35 approved these changes
Thanks

2025-01-21 17:05 UTC, eric-murray approved these changes

2025-01-22 09:18 UTC, luislopezcorpas approved these changes

2025-01-24 11:35 UTC, merged