Initial test plan
camaraproject/Tenure pull request #19
Opened 2024-12-19 11:38 UTC by fernandopradocabrillo

#### What type of PR is this?

Add one of the following kinds:
* enhancement/feature
* tests

#### What this PR does / why we need it:
Include initial basic test plan for the API

2025-01-02 16:29 UTC, eric-murray commented on code/Test_definitions/kyc-tenure.feature
> +        And the request body is set by default to a request body compliant with the schema
This last pre-condition can't be common for all tests, as tests 400.1, 400.2 and 400.4 are explicitly testing for non-compliance with the schema. I'd suggest to remove this pre-condition.

2025-01-02 16:30 UTC, eric-murray commented on code/Test_definitions/kyc-tenure.feature
> +        And if the response contains property "$.contractType" is one of ["PAYG", "PAYM", "Business"]
```suggestion
        And if the response contains property "$.contractType", the value is one of ["PAYG", "PAYM", "Business"]
```

2025-01-02 16:30 UTC, eric-murray commented on code/Test_definitions/kyc-tenure.feature
> +    Scenario: Validate successful response when tenureDateCheck is true
```suggestion
    Scenario: Validate successful response when tenureDateCheck is false
```

2025-01-02 16:31 UTC, eric-murray commented on code/Test_definitions/kyc-tenure.feature
> +        And if the response contains property "$.contractType" is one of ["PAYG", "PAYM", "Business"]
```suggestion
        And if the response contains property "$.contractType", the value is one of ["PAYG", "PAYM", "Business"]
```

2025-01-02 16:40 UTC, eric-murray commented on code/Test_definitions/kyc-tenure.feature
> +        And the response property "$.code" is "UNAUTHENTICATED" or "AUTHENTICATION_REQUIRED"
My understanding is that `AUTHENTICATION_REQUIRED` is returned when the access token has expired (i.e. was once valid, but is no longer because its lifetime has expired), whereas `UNAUTHENTICATED` is returned when the access token was either never valid, or has been "cancelled" for some other reason (e.g. token was reported stolen and thus voided).

But I agree that the API design guidelines are not at all clear on this point.

```suggestion
        And the response property "$.code" is "AUTHENTICATION_REQUIRED"
```

2025-01-02 16:41 UTC, eric-murray commented on code/Test_definitions/kyc-tenure.feature
> +        Given the header "Authorization" is set to an invalid access token
```suggestion
        Given the header "Authorization" is set to an invalid access token which is invalid for reasons other than lifetime expiry
```

2025-01-02 16:43 UTC, eric-murray commented on code/Test_definitions/kyc-tenure.feature
> +        And the request body property "$.phoneNumber" is compliant with the schema but does not identify a valid subscription
```suggestion
        And the request body property "$.phoneNumber" is compliant with the schema but does not identify a valid subscription managed by the API provider
```

2025-01-02 16:44 UTC, eric-murray commented on code/Test_definitions/kyc-tenure.feature
> +        Given that service is not supported for all phone numbers commercialized by the operator
"network operator" could also be replaced by "API provider"
```suggestion
        Given that service is not supported for all phone numbers managed by the network operator
```

2025-01-02 16:47 UTC, eric-murray commented
See also [C02-phoneNumber-errors.feature](https://github.com/camaraproject/Commonalities/blob/main/artifacts/testing/C02-phoneNumber-errors.feature), which defines an additional test `C02.01_phone_number_not_schema_compliant`

2025-01-08 10:28 UTC, fernandopradocabrillo commented on code/Test_definitions/kyc-tenure.feature
> +        And the request body is set by default to a request body compliant with the schema
This is the background fallback, I think it is supposed to be used only if the test doesn't specify something else. It sets initial conditions that can be overwrite in each scenario.

2025-01-08 10:42 UTC, fernandopradocabrillo commented on code/Test_definitions/kyc-tenure.feature
> +        And the response property "$.code" is "UNAUTHENTICATED" or "AUTHENTICATION_REQUIRED"
Yeah it's not very clear.. I opted for both since there is no consensus and other test plans have used different options. I think this way is a bit more flexible and we can always update it before the meta if there is a more clear path.

2025-01-15 10:57 UTC, fernandopradocabrillo commented
Hi @GillesInnov35 @eric-murray 
We need to have the test plan ready before jan 17 so we can proceed with the release. Please take a look

2025-01-15 13:01 UTC, GillesInnov35 submitted a review, later dismissed
Thanks a lot

2025-01-15 13:01 UTC, GillesInnov35 commented on code/Test_definitions/kyc-tenure.feature
> +        And the request body is set by default to a request body compliant with the schema
@eric-murray , @fernandopradocabrillo, as it is for most of others API I think we can keep it 
For my undersdtanding as said by Fernndo it can be overwritten by others tests. 
Gilles

2025-01-16 12:18 UTC, eric-murray commented on code/Test_definitions/kyc-tenure.feature
> +        And the request body is set by default to a request body compliant with the schema
OK, that's fine. For other APIs, I have seen they added a comment that the pre-conditions can be overwritten by individual tests.

2025-01-16 14:13 UTC, tanjadegroot requested changes
looks good _ some typos to be fixed

2025-01-16 14:13 UTC, tanjadegroot commented on code/Test_definitions/kyc-tenure.feature
> +    @check_device_swap_400.3_out_of_range
Copy error - device swap --> checkTenure

2025-01-16 14:13 UTC, tanjadegroot commented on code/Test_definitions/kyc-tenure.feature
> +    Scenario: Phone number not to included when can be deducted from the access token
Phone number "not to be included" or should not be included"

2025-01-16 14:58 UTC, fernandopradocabrillo commented
Thanks for the review @tanjadegroot 

Please @GillesInnov35 can you approve again? it got dismissed..

cc: @eric-murray

2025-01-16 15:02 UTC, GillesInnov35 approved these changes

2025-01-17 11:48 UTC, fernandopradocabrillo commented
hi @eric-murray @grgpapadopoulos  according to @tanjadegroot, everything seems fine with the release PR, we just need to merge the test plan to complete the process.
I can see that Gilles approved, please take a look in case we need to update anything

2025-01-21 08:53 UTC, merged